# Generated by Django 4.2.6 on 2023-10-30 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutmodel',
            name='name',
            field=models.CharField(default='workout', max_length=255),
        ),
    ]
