# Generated by Django 4.2.6 on 2023-11-14 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
        ('workout', '0002_workoutmodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutmodel',
            name='exercises',
            field=models.ManyToManyField(to='exercise.exercisemodel'),
        ),
        migrations.AlterField(
            model_name='workoutmodel',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.DeleteModel(
            name='WorkoutExerciseModel',
        ),
    ]
