# Generated by Django 4.2.6 on 2023-12-01 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0003_remove_programmodel_workouts'),
        ('workout', '0003_workoutmodel_exercises_alter_workoutmodel_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutmodel',
            name='exercises',
        ),
        migrations.AddField(
            model_name='workoutmodel',
            name='day',
            field=models.CharField(default='Monday', max_length=50),
        ),
        migrations.AddField(
            model_name='workoutmodel',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='program.programmodel'),
        ),
    ]
