# Generated by Django 4.2.6 on 2023-11-12 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=70)),
                ('description', models.TextField()),
                ('program_type', models.CharField(choices=[('Aerobics', 'Aerobics'), ('Lose Weight', 'Lose Weight'), ('Gain Muscle Mass', 'Gain Muscle Mass'), ('Be In Shape', 'Be In Shape'), ('Physical Activity', 'Physical Activity')], max_length=30)),
            ],
        ),
    ]
