# Generated by Django 4.2.6 on 2023-11-14 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_workoutmodel_exercises_alter_workoutmodel_name_and_more'),
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programmodel',
            name='program_type',
        ),
        migrations.AddField(
            model_name='programmodel',
            name='workouts',
            field=models.ManyToManyField(to='workout.workoutmodel'),
        ),
    ]
