# Generated by Django 4.2.6 on 2023-12-01 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_remove_programmodel_program_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programmodel',
            name='workouts',
        ),
    ]
