# Generated by Django 4.2.6 on 2023-11-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_workoutmodel_exercises_alter_workoutmodel_name_and_more'),
        ('program', '0004_alter_programmodel_workouts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmodel',
            name='workouts',
            field=models.ManyToManyField(null=True, to='workout.workoutmodel'),
        ),
    ]
