# Generated by Django 4.2.6 on 2023-12-01 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0004_remove_workoutmodel_exercises_workoutmodel_day_and_more'),
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.IntegerField()),
                ('weight', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SystemExercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('muscle_group', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='exercisemodel',
            name='workout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workout.workoutmodel'),
        ),
        migrations.RemoveField(
            model_name='exercisemodel',
            name='count_of_sets',
        ),
        migrations.AddField(
            model_name='exercisemodel',
            name='count_of_sets',
            field=models.ManyToManyField(to='exercise.setmodel'),
        ),
    ]
