# Generated by Django 4.2.6 on 2023-12-01 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_setmodel_systemexercises_exercisemodel_workout_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisemodel',
            name='count_of_sets',
            field=models.ManyToManyField(null=True, to='exercise.setmodel'),
        ),
    ]
