# Generated by Django 4.2.6 on 2023-12-01 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0003_alter_exercisemodel_count_of_sets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisemodel',
            name='count_of_sets',
            field=models.ManyToManyField(blank=True, null=True, to='exercise.setmodel'),
        ),
    ]
