# Generated by Django 4.2.6 on 2023-12-01 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0004_alter_exercisemodel_count_of_sets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercisemodel',
            old_name='count_of_sets',
            new_name='sets',
        ),
    ]
